In [1]:
import pandas as pd

df = pd.read_csv("../data/input.csv")
df

  item  quantity
0    A       999
1    B        20
2    C        30

In [2]:
df.shape

(3, 2)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   item      3 non-null      str
 1   quantity  3 non-null      int64
dtypes: int64(1), str(1)
memory usage: 180.0 bytes

In [4]:
df.describe()

         quantity
count    3.000000
mean   349.666667
std    562.361390
min     20.000000
25%     25.000000
50%     30.000000
75%    514.500000
max    999.000000

In [5]:
df.isna().sum()

item        0
quantity    0
dtype: int64

In [6]:
df["monthly_demand"] = [1000, 10, 15]

df["inventory_months"] = (
    df["quantity"] / df["monthly_demand"]
)

df

  item  quantity  monthly_demand  inventory_months
0    A       999            1000             0.999
1    B        20              10             2.000
2    C        30              15             2.000